sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t multi-container-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true multi-container-react-test npm run test

after_success:
  - docker build -t dockeramgupta04/multi-container-client ./client
  - docker build -t dockeramgupta04/multi-container-server ./server
  - docker build -t dockeramgupta04/multi-container-worker ./worker
  - docker build -t dockeramgupta04/multi-container-nginx ./nginx
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push these images to docker hub
  - docker push dockeramgupta04/multi-container-client
  - docker push dockeramgupta04/multi-container-server
  - docker push dockeramgupta04/multi-container-worker
  - docker push dockeramgupta04/multi-container-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-007445979313"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY