# anytime you use docker you should have super user permission, that's what we do below
# telling travis we will require docker 
# series of commnad to execute before our tests run
# conatains a group of scripts/commands to run that tells how to run tests suite to travis.

# on: branch: master => means whenever we push code to master deploy it on aws elastic branstalk

sudo: required 

language: generic

services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-007445979313"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
